### PR TITLE
Fixed the default namespace issue

### LINKED ISSUE #149: hydrophone --cleanup is broken
We are not setting default value for namespace flag when calling  `hydrophone --cleanup `  as a result its getting a blank namespace https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/service/init.go#L325
```
reeta@Reetas-MacBook-Pro homebrew-core % hydrophone --cleanup
17:35:42 INF API endpoint : https://127.0.0.1:50108
17:35:42 INF Server version : version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:42:59Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
17:35:42 ERR an empty namespace may not be set when a resource name is provided
reeta@Reetas-MacBook-Pro homebrew-core % 
```

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Currently if namespace is not passed and we run the command `bin/hydrophone --cleanup` then the command breaks so we can pass a default namespace it users run the command `bin/hydrophone --cleanup` then also the default namespace will be taken.

fixes #149 

Previous behaviour-
[
Screenshot from 2024-02-11 07-32-15
](url)

Current behaviour-
Screenshot from 2024-02-11 07-32-55

### CODE REVIEW

File: pkg/service/init.go [hunk 1]
```diff
@@ -323,6 +323,12 @@ func RunE2E(clientset *kubernetes.Clientset) {
 // Cleanup removes all resources created during E2E tests.
 func Cleanup(clientset *kubernetes.Clientset) {
 	namespace := viper.GetString("namespace")
+    
+	if namespace == "" {
```
Comment (reetasingh) [inline pkg/service/init.go:327]: @Bharadwajshivam28 A cleaner solution would be to reuse the ValidateArgs method https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/common/args.go#L52. its currently validating multiple things. maybe we can introduce a new method for validating namespace?

Comment (Bharadwajshivam28) [reply pkg/service/init.go:327]: Okay works for me... let me change it @reetasingh

**Comment by Bharadwajshivam28** [comment]
@reetasingh  I have made some changes..  
could you please review it?

File: pkg/common/args.go [hunk 2]
```diff
@@ -48,6 +48,12 @@ func PrintInfo(clientSet *kubernetes.Clientset, config *rest.Config) {
...
 // and creates the output directory if it doesn't exist
 
+func SetDefaultNamespace() {
+	if viper.Get("namespace") == "" {
+		viper.Set("namespace", DefaultNamespace)
+	}
+}
+
 func ValidateArgs() error {
 	if viper.Get("namespace") == "" {
```
Comment (reetasingh) [inline pkg/common/args.go:58]: reuse SetDefaultNamespace() here too.

Comment (Bharadwajshivam28) [reply pkg/common/args.go:58]: Okay...

File: pkg/common/args.go [hunk 3]
```diff
@@ -48,6 +48,12 @@ func PrintInfo(clientSet *kubernetes.Clientset, config *rest.Config) {
 // ValidateArgs validates the arguments passed to the program
 // and creates the output directory if it doesn't exist
 
+func SetDefaultNamespace() {
```
Comment (reetasingh) [inline pkg/common/args.go:51]: @Bharadwajshivam28 if possible can you  add unit test for this?

File: pkg/common/args.go [hunk 4]
```diff
@@ -48,6 +48,12 @@ func PrintInfo(clientSet *kubernetes.Clientset, config *rest.Config) {
 // ValidateArgs validates the arguments passed to the program
```
Comment (reetasingh) [inline pkg/common/args.go:48]: above comment is for ValidateArgs() method. I think you have not added it in right place

File: pkg/service/init.go [hunk 5]
```diff
@@ -322,7 +322,9 @@ func RunE2E(clientset *kubernetes.Clientset) {
 
 // Cleanup removes all resources created during E2E tests.
 func Cleanup(clientset *kubernetes.Clientset) {
+	common.SetDefaultNamespace()
 	namespace := viper.GetString("namespace")
+	fmt.Println("using namespace:", namespace)
```
Comment (reetasingh) [inline pkg/service/init.go:327]: use log instead of fmt see https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/common/args.go#L76 for example

File: pkg/common/args.go (hunk 4 above)
Comment (Bharadwajshivam28) [reply pkg/common/args.go:48]: Oh I missed it... Let me take a look at it..

Will push the changes soon..

File: pkg/common/args.go (hunk 2 above)
Comment (Bharadwajshivam28) [reply pkg/common/args.go:58]: > reuse SetDefaultNamespace() here too.

can you please elaborate this one? sorry but i not understood it..

File: pkg/common/args.go (hunk 3 above)
Comment (Bharadwajshivam28) [reply pkg/common/args.go:51]: > @Bharadwajshivam28 if possible can you add unit test for this?

I have implemented unit test but can you please elaborate this?
I will be happy to make the changes @reetasingh

File: pkg/service/init.go [hunk 6]
```diff
@@ -322,7 +322,9 @@ func RunE2E(clientset *kubernetes.Clientset) {
 
 // Cleanup removes all resources created during E2E tests.
 func Cleanup(clientset *kubernetes.Clientset) {
+	common.SetDefaultNamespace()
```
Comment (reetasingh) [inline pkg/service/init.go:325]: @Bharadwajshivam28 I think we can call this from cmd/root.go before calling `Cleanup`

File: pkg/common/args.go (hunk 3 above)
Comment (reetasingh) [reply pkg/common/args.go:48]: you can add the unit test for this in args_test.go

File: pkg/service/init.go (hunk 6 above)
Comment (Bharadwajshivam28) [reply pkg/service/init.go:325]: can you please make me understand this? I think you are saying to call this `common.SetDefaultNamespace()` from the root.go?

Comment (reetasingh) [reply pkg/service/init.go:325]: correct, here https://github.com/kubernetes-sigs/hydrophone/blob/main/cmd/root.go#L61

Comment (Bharadwajshivam28) [reply pkg/service/init.go:325]: oh.. you are saying to remove the line `common.SetDefaultNamespace()` from `init.go` and call it from here i```
f cleanup {
			common.SetDefaultNamespace()
			service.Cleanup(client.ClientSet)
```

from `root.go` file

Comment (reetasingh) [reply pkg/service/init.go:325]: yes

**Comment by Bharadwajshivam28** [comment]
@reetasingh I moved `common.SetDefaultNamespace()` to `root.go` file and tested it too...

**Comment by Bharadwajshivam28** [comment]
Just a small review i need that for the unit test what i understand for the **function SetDefaultNamespace** is-

Case 1
1) When Namespace is not passed, will set the **DefaultNamespace**.
2) After setting Namespace will check if the **current namespace matches the DefaultNamespace**.

Case 2
1) When **Namespace is already set.**
2) When Namesapce is set then we will **check that the Namespace should not be replaced with the Default Namespace.** Will **call the SetDefaultNamespace()** function before checking that the **namespace not gets replaced with DefaultNamespace.**

I saw the  **Pre declared test in args_test.go file.**

Is this way we are looking? as the function **SetDefaultNamespace** just checks and sets namespace.

**Comment by reetasingh** [comment]
> @reetasingh Just a small review i need that for the unit test what i understand for the **function SetDefaultNamespace** is-
> 
> Case 1
> 
> 1. When Namespace is not passed, will set the **DefaultNamespace**.
> 2. After setting Namespace will check if the **current namespace matches the DefaultNamespace**.
> 
> Case 2
> 
> 1. When **Namespace is already set.**
> 2. When Namesapce is set then we will **check that the Namespace should not be replaced with the Default Namespace.** Will **call the SetDefaultNamespace()** function before checking that the **namespace not gets replaced with DefaultNamespace.**
> 
> I saw the **Pre declared test in args_test.go file.**
> 
> Is this way we are looking? as the function **SetDefaultNamespace** just checks and sets namespace.

@Bharadwajshivam28 Its easier to review if you write the test case itself.  and yes, write for each of the test case above do viper.get("namespace") and check the value of namespace matches what is expected

**Comment by reetasingh** [comment]
I see the presumbit job is failing ```sigs.k8s.io/hydrophone/pkg/common	0.017s
FAIL	sigs.k8s.io/hydrophone/pkg/service [build failed]
FAIL
make: *** [Makefile:25: test] Error 1
``` can you run make test locally to see everything passes?

**Comment by Bharadwajshivam28** [comment]
> I see the presumbit job is failing
> 
> ```
> sigs.k8s.io/hydrophone/pkg/common	0.017s
> FAIL	sigs.k8s.io/hydrophone/pkg/service [build failed]
> FAIL
> make: *** [Makefile:25: test] Error 1
> ```
> 
> can you run make test locally to see everything passes?

ya let me check it

**Comment by Bharadwajshivam28** [comment]
> > @reetasingh Just a small review i need that for the unit test what i understand for the **function SetDefaultNamespace** is-
> > Case 1
> > 
> > 1. When Namespace is not passed, will set the **DefaultNamespace**.
> > 2. After setting Namespace will check if the **current namespace matches the DefaultNamespace**.
> > 
> > Case 2
> > 
> > 1. When **Namespace is already set.**
> > 2. When Namesapce is set then we will **check that the Namespace should not be replaced with the Default Namespace.** Will **call the SetDefaultNamespace()** function before checking that the **namespace not gets replaced with DefaultNamespace.**
> > 
> > I saw the **Pre declared test in args_test.go file.**
> > Is this way we are looking? as the function **SetDefaultNamespace** just checks and sets namespace.
> 
> @Bharadwajshivam28 Its easier to review if you write the test case itself. and yes, right for each of the test case above do viper.get("namespace") and check the value of namespace matches what is expected

Just a question @reetasingh  our default namespace is **conformance** which will be set if namespace is not passed and if user passes the namespace then we just need to skip the test. like we dont need to do any action if users passes the namespace =, we just need to take actions in when users don't pass namespace

**Comment by Bharadwajshivam28** [comment]
> I see the presumbit job is failing
> 
> ```
> sigs.k8s.io/hydrophone/pkg/common	0.017s
> FAIL	sigs.k8s.io/hydrophone/pkg/service [build failed]
> FAIL
> make: *** [Makefile:25: test] Error 1
> ```
> 
> can you run make test locally to see everything passes?

Pushed the code which fixes test
Screenshot from 2024-02-14 08-03-07

**Comment by rjsadow** [comment]
Please run `make fmt` and commit to make the verify test pass.

**Comment by Bharadwajshivam28** [comment]
Is there any more changes to be done mam @reetasingh
